from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol


@dataclass(frozen=True, slots=True)
class Result:
    ok: bool
    message: str


class MediaController(Protocol):
    def play(self) -> Result: ...
    def pause(self) -> Result: ...
    def next(self) -> Result: ...
    def previous(self) -> Result: ...
    def status(self) -> Result: ...
    def repeat_current(self) -> Result: ...
    def quieter(self) -> Result: ...
    def louder(self) -> Result: ...
    def stop(self) -> Result: ...
    def open_player(self) -> Result: ...
    def delete_current(self) -> Result: ...
